name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 0.18.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.7.0
  sqflite: #^1.3.1+1
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: master

  sqflite_common_ffi: ^1.1.1
  floor_annotation:
    #path: ../floor_annotation/
    git:
      url: https://github.com/zzd258147/floor.git
      path: floor_annotation
      ref: sqlcipher
  meta: ^1.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  collection: ^1.14.13
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  floor_generator:
    path: ../floor_generator/
  build_runner: ^1.10.3
  matcher: ^0.12.9
